/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bridgelabz.indianstatescensusanalyser;

import static org.junit.Assert.assertEquals;

import java.io.IOException;

import org.junit.Assert;
import org.junit.Test;
import org.junit.rules.ExpectedException;

public class CensusAnalyserTest 
{
	private static final String INDIA_CENSUS_CORRECT_DATA_CSV_FILE_PATH = "./src/test/resources/IndiaStateCensusCorrectData.csv";
	public static final String FILE_NOT_FOUND = "incorrectFilePath.csv";
	@Test
	public void givenStateCensusCsvFile_ShouldReturn_CorrectNumberOfRecords() {
		try {	
			StateCensusAnalyser censusAnalyser = new StateCensusAnalyser();
			int numOfRecords;
			numOfRecords = censusAnalyser.loadIndiaCensusData(INDIA_CENSUS_CORRECT_DATA_CSV_FILE_PATH);
			Assert.assertEquals(8, numOfRecords);
		} catch (CensusAnalyserException e) {
			
		}
		
	}
	
}